// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package pers.dxm.grpc.generatecode;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pers.dxm.grpc.generatecode.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
