// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package pers.dxm.grpc.generatecode;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pers.dxm.grpc.generatecode.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
