// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package pers.dxm.grpc.generatecode;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pers.dxm.grpc.generatecode.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pers.dxm.grpc.generatecode.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<pers.dxm.grpc.generatecode.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .pers.dxm.grpc.generatecode.StudentResponse studentResponse = 1;</code>
   */
  pers.dxm.grpc.generatecode.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .pers.dxm.grpc.generatecode.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .pers.dxm.grpc.generatecode.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends pers.dxm.grpc.generatecode.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .pers.dxm.grpc.generatecode.StudentResponse studentResponse = 1;</code>
   */
  pers.dxm.grpc.generatecode.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
